### ISSUE TITLE
Get-DscConfiguration failes with a casting error

### ISSUE THREAD

**Issue by FrodeOA** [PowerShell/xAdcsDeployment#15] opened 2016-04-18 12:19 UTC
On a WMF 4 machine I get the following error after running get-dscconfiguration (test works fine)

This event indicates that failure happens when LCM is processing the configuration. ErrorId is 0x1. ErrorDetail is The SendConfigurationApply function did not succeed.. ResourceId is [xAdcsCertificationAuthority]ADCS and SourceInfo is C:\WAP\SetupActiveDirectory\Config\Config-SetupActiveDirectory.ps1::85::9::xAdcsCertificationAuthority. ErrorMessage is Unable to cast object of type 'System.Management.Automation.PSCredential' to type 'Microsoft.Management.Infrastructure.Native.InstanceHandle'.
Parameter name: value.

**Comment by PlagueHO** [comment] 2016-04-18 22:20
@FrodeOA - I haven't seen an error like this before. Are you able to paste a copy of the xAdcsCertificationAuthority component of the config that is running?

**Comment by FrodeOA** [comment] 2016-04-19 05:39
Yeah sure, I'm just having a look at the CPS workload stuff for WAP to see what I can adapt for my own use. I've made some modifications with placement of stuff in other component and added encryption of the credentials but otherwise it's unmodified:

param
(
    [String]$DomainName,
    [String]$DomainNetbiosName,
    [PSCredential]$Credential,
    [PSCredential]$DomainCredential,
    [PSCredential]$SafeModeAdministratorPassword,
    [string]$EncryptionCertificateThumbprint
)
#endregion

#region Config Data
$certificate = dir Cert:\LocalMachine\my\$EncryptionCertificateThumbprint
$certificatePath = Join-Path -path $PSScriptRoot -childPath "EncryptionCertificate.cer"
Export-Certificate -Cert $certificate -FilePath $certificatePath | Out-Null
$configData = @{
    AllNodes = @(
        @{
            Nodename = "$env:COMPUTERNAME"
            CertificateFile = $certificatePath
            Thumbprint = $EncryptionCertificateThumbprint
            ServerRole = 'Active Directory Domain Controller'
            DomainName = $DomainName
            DomainNetbiosName = $DomainNetbiosName
            PSDscAllowPlainTextPassword = $false
            Credential = $Credential
            DomainCredential = $DomainCredential
            SafeModeCredential = $SafeModeAdministratorPassword
            Script1 = "Script1"
            RegistryPath = "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\FirstPartWorkload"
        }
    )
}
#endregion

#region First DC Configuration Script

if ((test-path C:\Windows\temp\First.txt) -eq $True)
{
configuration FirstDomainController
{
    Import-DscResource -ModuleName xComputerManagement, xActiveDirectory, xAdcsDeployment

    node $AllNodes.Where{$_.ServerRole -eq 'Active Directory Domain Controller'}.Nodename
    {    
        WindowsFeature AD-Domain-Services
        {
            Ensure = 'Present'
            Name = 'AD-Domain-Services'
        }
        
        WindowsFeature RSAT-DNS-Server
        {
            Ensure = 'Present'
            Name = 'RSAT-DNS-Server'
            DependsOn = '[WindowsFeature]AD-Domain-Services'
        }

        WindowsFeature RSAT-ADDS-Tools
        {
            Ensure = 'Present'
            Name = 'RSAT-ADDS-Tools'
            DependsOn = '[WindowsFeature]RSAT-DNS-Server'
        }
            
        xADDomain PrimaryDC
        {
            DomainAdministratorCredential = $Node.Credential
            DomainName = $Node.DomainName
            SafemodeAdministratorPassword = $Node.SafeModeCredential
            DatabasePath = "C:\NTDS"
            LogPath = "C:\NTDS"
            SysvolPath = "C:\SYSVOL"
            DependsOn = "[WindowsFeature]AD-Domain-Services","[WindowsFeature]RSAT-DNS-Server"
        }

        WindowsFeature ADCS-Cert-Authority 
        { 
            Ensure = 'Present' 
            Name = 'ADCS-Cert-Authority' 
            DependsOn = '[xADDomain]PrimaryDC'
        } 

        xAdcsCertificationAuthority ADCS 
        { 
            Ensure = 'Present' 
            Credential = $node.Credential
            CAType = 'EnterpriseRootCA' 
            DependsOn = '[WindowsFeature]ADCS-Cert-Authority'               
        } 
        WindowsFeature ADCS-Web-Enrollment 
        { 
            Ensure = 'Present' 
            Name = 'ADCS-Web-Enrollment' 
            DependsOn = '[WindowsFeature]ADCS-Cert-Authority' 
        } 

        xADCSWebEnrollment CertSrv 
        { 
            Ensure = 'Present' 
            Name = 'CertSrv' 
            Credential = $node.Credential
            DependsOn = '[WindowsFeature]ADCS-Web-Enrollment','[xADCSCertificationAuthority]ADCS' 
        }  

        Registry DeploymentComplete
        {
            Ensure = "Present"
            Key = $Node.RegistryPath
            ValueName = $Node.Script1
            ValueData = "Done"
            ValueType = "String"
            DependsOn = '[xADCSWebEnrollment]CertSrv'
        }

        LocalConfigurationManager
        {
            CertificateId = $node.Thumbprint
            ConfigurationMode = 'ApplyandAutoCorrect'
            RebootNodeIfNeeded = $True
        }
    }
}

FirstDomainController -ConfigurationData $configData -OutputPath $PSScriptRoot
}

**Comment by PlagueHO** [comment] 2016-04-19 20:48
That all looks fine to me. 

Can you confirm the $Credential parameter that is being passed in is a valid PSCredential object? E.g. usually created using something like this:
```
$Password = (ConvertTo-SecureString 'Somepassword' -AsPlainText -Force)
$Credential = New-Object System.Management.Automation.PSCredential 'Administrator', $Password
```
I know that is probably pretty unlikely the cause because the $Credential is used earlier on in the script.

I use this resource in my own projects, but I usually add a few more parameters to it:
```powershell
        xADCSCertificationAuthority ConfigCA
        {
            Ensure = 'Present'
            Credential = $Node.Credential
            CAType = 'EnterpriseRootCA'
            CACommonName = "LABBUILDER.COM Root CA"
            CADistinguishedNameSuffix = "DC=LABBUILDER,DC=COM"
            OverwriteExistingCAinDS  = $True
            CryptoProviderName = 'RSA#Microsoft Software Key Storage Provider'
            HashAlgorithmName = 'SHA256'
            KeyLength = 4096
    }
```
Are you able to try with the additional parameters I've added here? If I can identify the difference that causes it to work on my nodes and not yours then I might be able to resolve it. :)

**Comment by FrodeOA** [comment] 2016-04-20 07:10
I gave it a go and I got the same error. I also tried the configuration with and without encryption just to give it a go and I got the same error.

The credential is built using this:
$LocalAdminCredential = New-Object System.Management.Automation.PSCredential ($($Credential.split(":")[0]), $(ConvertTo-SecureString -String $Credential.split(":")[1] -AsPlainText -Force)) so it's a valid credential object, $credential is a string passed from the SPF server in a $username:$password format hence the splitting.

**Comment by PlagueHO** [comment] 2016-04-20 08:19
Is the AD CS node Windows Server 2012 or 2012 R2? I've only used this on 2012 R2 and 2016 myself.

Are you able to post a copy of the full verbose output from Start-DSCConfiguration here?

**Comment by FrodeOA** [comment] 2016-04-20 12:26
It's a 2012 R2 node.

Here's the logs:
VERBOSE: Performing the operation "Start-DscConfiguration: SendMetaConfigurationApply" on target "MSFT_DSCLocalConfigurationManager".
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendMetaConfigurationApply,'className' = MSFT_DSCLocalC
onfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer  with user sid S-1-5-21-48010005-1724078836-467140477-500.
VERBOSE: []: LCM:  [ Start  Set      ]
VERBOSE: []: LCM:  [ Start  Resource ]  [MSFT_DSCMetaConfiguration]
VERBOSE: []: LCM:  [ Start  Set      ]  [MSFT_DSCMetaConfiguration]
VERBOSE: []: LCM:  [ End    Set      ]  [MSFT_DSCMetaConfiguration]  in 0.1410 seconds.
VERBOSE: []: LCM:  [ End    Resource ]  [MSFT_DSCMetaConfiguration]
VERBOSE: []: LCM:  [ End    Set      ]    in  0.3284 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Set-DscLocalConfigurationManager finished in 0.601 seconds.
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfi
gurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer  with user sid S-1-5-21-48010005-1724078836-467140477-500.
VERBOSE: []: LCM:  [ Start  Set      ]
VERBOSE: []: LCM:  [ Start  Resource ]  [[WindowsFeature]AD-Domain-Services]
VERBOSE: []: LCM:  [ Start  Test     ]  [[WindowsFeature]AD-Domain-Services]
VERBOSE: []:                            [[WindowsFeature]AD-Domain-Services] The operation 'Get-WindowsFeature' started: AD-Domain-S
ervices
VERBOSE: []:                            [[WindowsFeature]AD-Domain-Services] The operation 'Get-WindowsFeature' succeeded: AD-Domain
-Services
VERBOSE: []: LCM:  [ End    Test     ]  [[WindowsFeature]AD-Domain-Services]  in 1.5160 seconds.
VERBOSE: []: LCM:  [ Start  Set      ]  [[WindowsFeature]AD-Domain-Services]
VERBOSE: []:                            [[WindowsFeature]AD-Domain-Services] Installation started...
VERBOSE: []:                            [[WindowsFeature]AD-Domain-Services] Continue with installation?
VERBOSE: []:                            [[WindowsFeature]AD-Domain-Services] Prerequisite processing started...
VERBOSE: []:                            [[WindowsFeature]AD-Domain-Services] Prerequisite processing succeeded.
VERBOSE: []:                            [[WindowsFeature]AD-Domain-Services] Installation succeeded.
VERBOSE: []:                            [[WindowsFeature]AD-Domain-Services] successfully installed the feature AD-Domain-Services
VERBOSE: []: LCM:  [ End    Set      ]  [[WindowsFeature]AD-Domain-Services]  in 33.7500 seconds.
VERBOSE: []: LCM:  [ End    Resource ]  [[WindowsFeature]AD-Domain-Services]
VERBOSE: []: LCM:  [ Start  Resource ]  [[WindowsFeature]RSAT-DNS-Server]
VERBOSE: []: LCM:  [ Start  Test     ]  [[WindowsFeature]RSAT-DNS-Server]
VERBOSE: []:                            [[WindowsFeature]RSAT-DNS-Server] The operation 'Get-WindowsFeature' started: RSAT-DNS-Server
VERBOSE: []:                            [[WindowsFeature]RSAT-DNS-Server] The operation 'Get-WindowsFeature' succeeded: RSAT-DNS-Server
VERBOSE: []: LCM:  [ End    Test     ]  [[WindowsFeature]RSAT-DNS-Server]  in 1.2390 seconds.
VERBOSE: []: LCM:  [ Start  Set      ]  [[WindowsFeature]RSAT-DNS-Server]
VERBOSE: []:                            [[WindowsFeature]RSAT-DNS-Server] Installation started...
VERBOSE: []:                            [[WindowsFeature]RSAT-DNS-Server] Continue with installation?
VERBOSE: []:                            [[WindowsFeature]RSAT-DNS-Server] Prerequisite processing started...
VERBOSE: []:                            [[WindowsFeature]RSAT-DNS-Server] Prerequisite processing succeeded.
VERBOSE: []:                            [[WindowsFeature]RSAT-DNS-Server] Installation succeeded.
VERBOSE: []:                            [[WindowsFeature]RSAT-DNS-Server] successfully installed the feature RSAT-DNS-Server
VERBOSE: []: LCM:  [ End    Set      ]  [[WindowsFeature]RSAT-DNS-Server]  in 10.8020 seconds.
VERBOSE: []: LCM:  [ End    Resource ]  [[WindowsFeature]RSAT-DNS-Server]
VERBOSE: []: LCM:  [ Start  Resource ]  [[WindowsFeature]RSAT-ADDS-Tools]
VERBOSE: []: LCM:  [ Start  Test     ]  [[WindowsFeature]RSAT-ADDS-Tools]
VERBOSE: []:                            [[WindowsFeature]RSAT-ADDS-Tools] The operation 'Get-WindowsFeature' started: RSAT-ADDS-Tools
VERBOSE: []:                            [[WindowsFeature]RSAT-ADDS-Tools] The operation 'Get-WindowsFeature' succeeded: RSAT-ADDS-Tools
VERBOSE: []: LCM:  [ End    Test     ]  [[WindowsFeature]RSAT-ADDS-Tools]  in 0.2970 seconds.
VERBOSE: []: LCM:  [ Start  Set      ]  [[WindowsFeature]RSAT-ADDS-Tools]
VERBOSE: []:                            [[WindowsFeature]RSAT-ADDS-Tools] Installation started...
VERBOSE: []:                            [[WindowsFeature]RSAT-ADDS-Tools] Continue with installation?
VERBOSE: []:                            [[WindowsFeature]RSAT-ADDS-Tools] Prerequisite processing started...
VERBOSE: []:                            [[WindowsFeature]RSAT-ADDS-Tools] Prerequisite processing succeeded.
VERBOSE: []:                            [[WindowsFeature]RSAT-ADDS-Tools] Installation succeeded.
VERBOSE: []:                            [[WindowsFeature]RSAT-ADDS-Tools] successfully installed the feature RSAT-ADDS-Tools
VERBOSE: []: LCM:  [ End    Set      ]  [[WindowsFeature]RSAT-ADDS-Tools]  in 12.1560 seconds.
VERBOSE: []: LCM:  [ End    Resource ]  [[WindowsFeature]RSAT-ADDS-Tools]
VERBOSE: []: LCM:  [ Start  Resource ]  [[xADDomain]PrimaryDC]
VERBOSE: []: LCM:  [ Start  Test     ]  [[xADDomain]PrimaryDC]
VERBOSE: []:                            [[xADDomain]PrimaryDC] Resolving 'frode.local' ...
VERBOSE: []:                            [[xADDomain]PrimaryDC] Current node is not running AD WS, and hence is not a domain controller.
VERBOSE: []: LCM:  [ End    Test     ]  [[xADDomain]PrimaryDC]  in 1.0310 seconds.
VERBOSE: []: LCM:  [ Start  Set      ]  [[xADDomain]PrimaryDC]
VERBOSE: []:                            [[xADDomain]PrimaryDC] Checking if domain 'frode.local' is present ...
VERBOSE: []:                            [[xADDomain]PrimaryDC] Verified that domain 'frode.local' is not already present, continuing ...
VERBOSE: []:                            [[xADDomain]PrimaryDC] Domain 'frode.local' is NOT present. Creating forest 'frode.local' ...
VERBOSE: []:                            [[xADDomain]PrimaryDC] Active Directory Domain Services Setup
VERBOSE: []:                            [[xADDomain]PrimaryDC] Validating environment and parameters...
WARNING: []:                            [[xADDomain]PrimaryDC] Windows Server 2012 R2 domain controllers have a default for the security setting named 
"Allow cryptography algorithms compatible with Windows NT 4.0" that prevents weaker cryptography algorithms when establishing security channel sessions.

For more information about this setting, see Knowledge Base article 942564 (http://go.microsoft.com/fwlink/?LinkId=104751).
WARNING: []:                            [[xADDomain]PrimaryDC] This computer has at least one physical network adapter that does not have static IP add
ress(es) assigned to its IP Properties. If both IPv4 and IPv6 are enabled for a network adapter, both IPv4 and IPv6 static IP addresses should be assigned to both 
IPv4 and IPv6 Properties of the physical network adapter. Such static IP address(es) assignment should be done to all the physical network adapters for reliable Do
main Name System (DNS) operation.
WARNING: []:                            [[xADDomain]PrimaryDC] A delegation for this DNS server cannot be created because the authoritative parent zone
 cannot be found or it does not run Windows DNS server. If you are integrating with an existing DNS infrastructure, you should manually create a delegation to this
 DNS server in the parent zone to ensure reliable name resolution from outside the domain "frode.local". Otherwise, no action is required.
VERBOSE: []:                            [[xADDomain]PrimaryDC] ----------------------------------------
VERBOSE: []:                            [[xADDomain]PrimaryDC] The following actions will be performed:
VERBOSE: []:                            [[xADDomain]PrimaryDC] Configure this server as the first Active Directory domain controller in a new forest.

The new domain name is "frode.local". This is also the name of the new forest.

The NetBIOS name of the domain is "FRODE".

Forest Functional Level: Windows Server 2012 R2

Domain Functional Level: Windows Server 2012 R2

Site: Default-First-Site-Name

Additional Options:
  Read-only domain controller: "No"
  Global catalog: Yes
  DNS Server: Yes

Create DNS Delegation: No

Database folder: C:\NTDS
Log file folder: C:\NTDS
SYSVOL folder: C:\SYSVOL

The DNS Server service will be installed on this computer.
The DNS Server service will be configured on this computer.
This computer will be configured to use this DNS server as its preferred DNS server.

The password of the new domain Administrator will be the same as the password of the local Administrator of this computer.
VERBOSE: []:                            [[xADDomain]PrimaryDC] ----------------------------------------
VERBOSE: []:                            [[xADDomain]PrimaryDC] Active Directory Domain Services Setup
VERBOSE: []:                            [[xADDomain]PrimaryDC] Validating environment and parameters...
WARNING: []:                            [[xADDomain]PrimaryDC] Windows Server 2012 R2 domain controllers have a default for the security setting named 
"Allow cryptography algorithms compatible with Windows NT 4.0" that prevents weaker cryptography algorithms when establishing security channel sessions.

For more information about this setting, see Knowledge Base article 942564 (http://go.microsoft.com/fwlink/?LinkId=104751).
WARNING: []:                            [[xADDomain]PrimaryDC] This computer has at least one physical network adapter that does not have static IP add
ress(es) assigned to its IP Properties. If both IPv4 and IPv6 are enabled for a network adapter, both IPv4 and IPv6 static IP addresses should be assigned to both 
IPv4 and IPv6 Properties of the physical network adapter. Such static IP address(es) assignment should be done to all the physical network adapters for reliable Do
main Name System (DNS) operation.
WARNING: []:                            [[xADDomain]PrimaryDC] A delegation for this DNS server cannot be created because the authoritative parent zone
 cannot be found or it does not run Windows DNS server. If you are integrating with an existing DNS infrastructure, you should manually create a delegation to this
 DNS server in the parent zone to ensure reliable name resolution from outside the domain "frode.local". Otherwise, no action is required.
VERBOSE: []:                            [[xADDomain]PrimaryDC] ----------------------------------------
VERBOSE: []:                            [[xADDomain]PrimaryDC] The following actions will be performed:
VERBOSE: []:                            [[xADDomain]PrimaryDC] Configure this server as the first Active Directory domain controller in a new forest.

The new domain name is "frode.local". This is also the name of the new forest.

The NetBIOS name of the domain is "FRODE".

Forest Functional Level: Windows Server 2012 R2

Domain Functional Level: Windows Server 2012 R2

Site: Default-First-Site-Name

Additional Options:
  Read-only domain controller: "No"
  Global catalog: Yes
  DNS Server: Yes

Create DNS Delegation: No

Database folder: C:\NTDS
Log file folder: C:\NTDS
SYSVOL folder: C:\SYSVOL

The DNS Server service will be installed on this computer.
The DNS Server service will be configured on this computer.
This computer will be configured to use this DNS server as its preferred DNS server.

The password of the new domain Administrator will be the same as the password of the local Administrator of this computer.
VERBOSE: []:                            [[xADDomain]PrimaryDC] ----------------------------------------
VERBOSE: []:                            [[xADDomain]PrimaryDC] Press CTRL-C to: Cancel
VERBOSE: []:                            [[xADDomain]PrimaryDC] Active Directory Domain Services is now installed on this computer for the domain "frode
.local".

This Active Directory domain controller is assigned to the site "Default-First-Site-Name". You can manage sites with the Active Directory Sites and Services admini
strative tool.
VERBOSE: []:                            [[xADDomain]PrimaryDC] Created forest 'frode.local'.
VERBOSE: []: LCM:  [ End    Set      ]  [[xADDomain]PrimaryDC]  in 88.3020 seconds.
VERBOSE: []: LCM:  [ End    Resource ]  [[xADDomain]PrimaryDC]
VERBOSE: []:                            [] A reboot is required to progress further. Please reboot the system.
VERBOSE: []: LCM:  [ End    Set      ]    in  194.1032 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 153.19 seconds

[]:                            [] A pending configuration exists. DSC will process a set request on the pending configuration.
[]:                            [] Starting consistency engine.
[]: LCM:  [ Start  Test     ]  [[WindowsFeature]AD-Domain-Services]  
[]: LCM:  [ Start  Resource ]  [[WindowsFeature]AD-Domain-Services]  
[]:                            [[WindowsFeature]AD-Domain-Services] The operation 'Get-WindowsFeature' started: AD-Domain-Services
[]:                            [[WindowsFeature]AD-Domain-Services] The operation 'Get-WindowsFeature' succeeded: AD-Domain-Services
[]: LCM:  [ End    Resource ]  [[WindowsFeature]AD-Domain-Services]  
[]: LCM:  [ Skip   Set      ]  [[WindowsFeature]AD-Domain-Services]  
[]: LCM:  [ End    Test     ]  [[WindowsFeature]AD-Domain-Services]  in 14.5110 seconds.
[]: LCM:  [ Start  Test     ]  [[WindowsFeature]RSAT-DNS-Server]  
[]: LCM:  [ Start  Resource ]  [[WindowsFeature]RSAT-DNS-Server]  
[]:                            [[WindowsFeature]RSAT-DNS-Server] The operation 'Get-WindowsFeature' started: RSAT-DNS-Server
[]:                            [[WindowsFeature]RSAT-DNS-Server] The operation 'Get-WindowsFeature' succeeded: RSAT-DNS-Server
[]: LCM:  [ Start  Resource ]  [[WindowsFeature]RSAT-ADDS-Tools]  
[]: LCM:  [ End    Resource ]  [[WindowsFeature]RSAT-DNS-Server]  
[]: LCM:  [ End    Test     ]  [[WindowsFeature]RSAT-DNS-Server]  in 0.4850 seconds.
[]: LCM:  [ Skip   Set      ]  [[WindowsFeature]RSAT-DNS-Server]  
[]: LCM:  [ Start  Test     ]  [[WindowsFeature]RSAT-ADDS-Tools]  
[]:                            [[WindowsFeature]RSAT-ADDS-Tools] The operation 'Get-WindowsFeature' started: RSAT-ADDS-Tools
[]: LCM:  [ End    Resource ]  [[WindowsFeature]RSAT-ADDS-Tools]  
[]: LCM:  [ Start  Resource ]  [[xADDomain]PrimaryDC]  
[]: LCM:  [ Skip   Set      ]  [[WindowsFeature]RSAT-ADDS-Tools]  
[]:                            [[WindowsFeature]RSAT-ADDS-Tools] The operation 'Get-WindowsFeature' succeeded: RSAT-ADDS-Tools
[]: LCM:  [ End    Test     ]  [[WindowsFeature]RSAT-ADDS-Tools]  in 0.2040 seconds.
[]: LCM:  [ Start  Test     ]  [[xADDomain]PrimaryDC]  
[]:                            [[xADDomain]PrimaryDC] Resolving 'frode.local' ...
[]:                            [[xADDomain]PrimaryDC] Domain 'frode.local' is present. Looking for DCs ...
[]:                            [[xADDomain]PrimaryDC] Found domain controller '' in domain 'frode.local'.
[]: LCM:  [ Start  Test     ]  [[WindowsFeature]ADCS-Cert-Authority]  
[]: LCM:  [ End    Test     ]  [[xADDomain]PrimaryDC]  in 2.2370 seconds.
[]:                            [[xADDomain]PrimaryDC] Current node '' is already a domain controller for domain 'frode.local'.
[]: LCM:  [ End    Resource ]  [[xADDomain]PrimaryDC]  
[]: LCM:  [ Skip   Set      ]  [[xADDomain]PrimaryDC]  
[]:                            [[xADDomain]PrimaryDC] Found parent domain '', expected ''.
[]: LCM:  [ Start  Resource ]  [[WindowsFeature]ADCS-Cert-Authority]  
[]:                            [[WindowsFeature]ADCS-Cert-Authority] The operation 'Get-WindowsFeature' started: ADCS-Cert-Authority
[]: LCM:  [ Start  Set      ]  [[WindowsFeature]ADCS-Cert-Authority]  
[]:                            [[WindowsFeature]ADCS-Cert-Authority] The operation 'Get-WindowsFeature' succeeded: ADCS-Cert-Authority
[]: LCM:  [ End    Test     ]  [[WindowsFeature]ADCS-Cert-Authority]  in 3.2300 seconds.
[]:                            [[WindowsFeature]ADCS-Cert-Authority] Installation started... 
[]:                            [[WindowsFeature]ADCS-Cert-Authority] Continue with installation?
[]:                            [[WindowsFeature]ADCS-Cert-Authority] Prerequisite processing started...
[]:                            [[WindowsFeature]ADCS-Cert-Authority] Prerequisite processing succeeded.
[]:                            [[WindowsFeature]ADCS-Cert-Authority] Installation succeeded.
[]: LCM:  [ Start  Test     ]  [[xAdcsCertificationAuthority]ADCS]  
[]: LCM:  [ End    Resource ]  [[WindowsFeature]ADCS-Cert-Authority]  
[]:                            [[WindowsFeature]ADCS-Cert-Authority] successfully installed the feature ADCS-Cert-Authority
[]: LCM:  [ Start  Resource ]  [[xAdcsCertificationAuthority]ADCS]  
[]: LCM:  [ End    Set      ]  [[WindowsFeature]ADCS-Cert-Authority]  in 29.5440 seconds.
[]:                            [[xAdcsCertificationAuthority]ADCS] Calling InitializeDefaults method on the setup object.
[]:                            [[xAdcsCertificationAuthority]ADCS] Setting the AllowAdministratorInteraction property to False.
[]:                            [[xAdcsCertificationAuthority]ADCS] Certification Authority will be installed with a new key.
[]:                            [[xAdcsCertificationAuthority]ADCS] Setting the CAType property to EnterpriseRootCA.
[]: LCM:  [ Start  Set      ]  [[xAdcsCertificationAuthority]ADCS]  
[]: LCM:  [ End    Test     ]  [[xAdcsCertificationAuthority]ADCS]  in 0.6130 seconds.
[]:                            [[xAdcsCertificationAuthority]ADCS] Calling InitializeDefaults method on the setup object.
[]:                            [[xAdcsCertificationAuthority]ADCS] Certification Authority will be installed with a new key.
[]:                            [[xAdcsCertificationAuthority]ADCS] Setting the CAType property to EnterpriseRootCA.
[]:                            [[xAdcsCertificationAuthority]ADCS] Setting the AllowAdministratorInteraction property to False.
[]:                            [[xAdcsCertificationAuthority]ADCS] Calling install method.
[]: LCM:  [ Start  Test     ]  [[WindowsFeature]ADCS-Web-Enrollment]  
[]: LCM:  [ Start  Resource ]  [[WindowsFeature]ADCS-Web-Enrollment]  
[]: LCM:  [ End    Set      ]  [[xAdcsCertificationAuthority]ADCS]  in 1.1290 seconds.
[]: LCM:  [ End    Resource ]  [[xAdcsCertificationAuthority]ADCS]  
[]:                            [[WindowsFeature]ADCS-Web-Enrollment] The operation 'Get-WindowsFeature' started: ADCS-Web-Enrollment
[]:                            [[WindowsFeature]ADCS-Web-Enrollment] The operation 'Get-WindowsFeature' succeeded: ADCS-Web-Enrollment
[]: LCM:  [ End    Test     ]  [[WindowsFeature]ADCS-Web-Enrollment]  in 0.2030 seconds.
[]:                            [[WindowsFeature]ADCS-Web-Enrollment] Installation started... 
[]: LCM:  [ Start  Set      ]  [[WindowsFeature]ADCS-Web-Enrollment]  
[]:                            [[WindowsFeature]ADCS-Web-Enrollment] Continue with installation?
[]:                            [[WindowsFeature]ADCS-Web-Enrollment] Prerequisite processing started...
[]:                            [[WindowsFeature]ADCS-Web-Enrollment] Prerequisite processing succeeded.
[]: LCM:  [ End    Resource ]  [[WindowsFeature]ADCS-Web-Enrollment]  
[]: LCM:  [ Start  Resource ]  [[xAdcsWebEnrollment]CertSrv]  
[]:                            [[WindowsFeature]ADCS-Web-Enrollment] successfully installed the feature ADCS-Web-Enrollment
[]: LCM:  [ End    Set      ]  [[WindowsFeature]ADCS-Web-Enrollment]  in 37.1880 seconds.
[]:                            [[WindowsFeature]ADCS-Web-Enrollment] Installation succeeded.
[]: LCM:  [ Start  Test     ]  [[xAdcsWebEnrollment]CertSrv]  
[]:                            [[xAdcsWebEnrollment]CertSrv] Calling InitializeDefaults method on the setup object.
[]: LCM:  [ Start  Set      ]  [[xAdcsWebEnrollment]CertSrv]  
[]: LCM:  [ End    Test     ]  [[xAdcsWebEnrollment]CertSrv]  in 0.0470 seconds.
[]:                            [[xAdcsWebEnrollment]CertSrv] Calling InitializeDefaults method on the setup object.
[]:                            [[xAdcsWebEnrollment]CertSrv] Calling install method.
[]: LCM:  [ End    Resource ]  [[xAdcsWebEnrollment]CertSrv]  
[]: LCM:  [ End    Set      ]  [[xAdcsWebEnrollment]CertSrv]  in 0.4220 seconds.
[]: LCM:  [ Start  Resource ]  [[Registry]DeploymentComplete]  
[]: LCM:  [ Start  Test     ]  [[Registry]DeploymentComplete]  
[]: LCM:  [ Start  Set      ]  [[Registry]DeploymentComplete]  
[]:                            [[Registry]DeploymentComplete] Registry key 'HKLM:\software\microsoft\firstpartworkload' does not exist
[]: LCM:  [ End    Test     ]  [[Registry]DeploymentComplete]  in 0.6400 seconds.
[]:                            [[Registry]DeploymentComplete] (SET) Create registry key 'HKLM:\software\microsoft\firstpartworkload'
[]: LCM:  [ End    Set      ]  [[Registry]DeploymentComplete]  in 0.1880 seconds.
[]: LCM:  [ End    Resource ]  [[Registry]DeploymentComplete]  
[]:                            [[Registry]DeploymentComplete] (SET) Set registry key value 'HKLM:\software\microsoft\firstpartworkload\Script1' to 'Done' of type 'String'
[]:                            [] Consistency check completed.

**Comment by PlagueHO** [comment] 2016-12-20 06:31
@FrodeOA - if you are about and still having trouble with this, are you able to try with the 1.1.0.0 version of this resource? I reworked a lot of it to make it play a bit nicer.

**Comment by FrodeOA** [comment] 2016-12-21 08:40
I ran a test and it seems to be working fine with WMF 5, I haven't been able to recreate the bug

**Comment by PlagueHO** [comment] 2016-12-24 01:39
HI @FrodeOA - that is great to hear. Is it OK to close this issue? You can always reopen it if it reoccurs.

**Comment by PlagueHO** [comment] 2017-11-10 21:44
Closing this issue.

**Closed by PlagueHO** 2017-11-10 21:44 UTC
Labels: bug, waiting for the author
